version: '3'
services:
  app:
    image: node:10-alpine
    container_name: piratestories-app
    depends_on:
      - postgres
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: 'npm run dev'
    ports:
      - 8888:8888

  postgres:
    image: postgres
    container_name: piratestories-db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
