version: '3'
services:
  app:
    image: node:10-alpine
    container_name: piratestories-app
    depends_on:
      - postgres
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: 'npm run start:dev'
    environment:
      APP_PORT: 3000
      DATABASE_URL: 'postgres://postgres:postgres@postgres:5432/postgres'
    ports:
      - 3000:3000

  postgres:
    image: postgres
    container_name: piratestories-db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
       - ./pgadmin:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    restart: unless-stopped
